# GitHub Pages Jekyll Configuration
title: "Instruction Template Specification"
description: "A specification for instruction-generative content templates that compile into AI prompts"
url: "https://your-username.github.io"
baseurl: "/instruction-template-specification"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections for organizing content
collections:
  examples:
    output: true
    permalink: /:collection/:name/

# Default settings for different content types
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "_examples"
      type: "examples"
    values:
      layout: "example"

# Navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "Specification"
    url: "/specification"
  - title: "Getting Started"
    url: "/getting-started"
  - title: "Examples"
    url: "/examples"
  - title: "Schema"
    url: "/schema/v1.0/"

# Schema information
schema:
  version: "1.0"
  base_url: "/schema/v1.0"
  template_schema: "/schema/v1.0/template.json"
  types_schema: "/schema/v1.0/standard-types.json"

# GitHub repository
repository: "your-username/instruction-template-specification"

# Exclude from processing
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata

# Include files that start with underscore
include:
  - _config.yml